nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']  # Remplacez par l'URL de votre application front-end
            allow_methods: ['POST', 'OPTIONS', 'GET']  # Liste des méthodes autorisées
            allow_headers: ['Content-Type', 'Authorization']  # Liste des en-têtes autorisés
            max_age: 3600